#!/usr/bin/env php
<?php
/**
 * This file is part of the Dynamic Suite framework.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package DynamicSuite
 * @author Grant Martin <commgdog@gmail.com>
 * @copyright 2021 Dynamic Suite Team
 */

namespace DynamicSuite;
use DynamicSuite\Util\CLI;
use PDO;

/**
 * Create environment.
 */
require_once __DIR__ . '/../include/create_instance.php';

/**
 * Connect to the database.
 */
DynamicSuite::$db->connect();

/**
 * Dump information.
 */
CLI::out('-- Environment');
CLI::out('  Server OS: ' . php_uname());
CLI::out('    PHP Ver: ' . phpversion());
CLI::out('   Root Dir: ' . DS_ROOT_DIR);
CLI::out('-- Instance');
CLI::out(' DS Version: ' . DS_VERSION);
CLI::out('       Time: ' . microtime(true));
CLI::out('       APCU: ' . (DS_CACHING ? 'YES' : 'NO'));
CLI::out('-- Database');
CLI::out('        DSN: ' . DynamicSuite::$cfg->db_dsn);
CLI::out('       User: ' . DynamicSuite::$cfg->db_user);
CLI::out(' Client Ver: ' . DynamicSuite::$db->conn->getAttribute(PDO::ATTR_CLIENT_VERSION));
CLI::out(' Server Ver: ' . DynamicSuite::$db->conn->getAttribute(PDO::ATTR_SERVER_VERSION));
CLI::out('     Driver: ' . DynamicSuite::$db->conn->getAttribute(PDO::ATTR_DRIVER_NAME));
CLI::out('-- Packages');
if (empty(Packages::$loaded)) {
    CLI::out('  No packages loaded');
}
foreach (Packages::$loaded as $package) {
    CLI::out("  $package->package_id");
    CLI::out("    Name:        $package->name");
    CLI::out("    Author:      $package->author");
    CLI::out("    Version:     $package->version");
    CLI::out("    Description: $package->description");
    CLI::out("    License:     $package->license");
}