#!/usr/bin/env php
<?php
/*
 * Dynamic Suite
 * Copyright (C) 2020 Dynamic Suite Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 */

namespace DynamicSuite;
use DynamicSuite\Core\Instance;
use DynamicSuite\Util\CLI;
use DynamicSuite\Package\Structure;
use PDO;

set_time_limit(0);
ini_set('memory_limit', -1);

// Create environment
require_once realpath(__DIR__ . '/create_instance.php');

/** @var Instance $ds */

CLI::out('-- Environment');
CLI::out('  Server OS: ' . php_uname());
CLI::out('    PHP Ver: ' . phpversion());
CLI::out('   Root Dir: ' . DS_ROOT_DIR);
CLI::out('-- Instance');
CLI::out(' DS Version: ' . DS_VERSION);
CLI::out('       Time: ' . date('Y-m-d H:i:s'));
CLI::out('       APCU: ' . (DS_APCU ? 'YES' : 'NO'));
CLI::out('-- Database');
CLI::out('        DSN: ' . $ds->cfg->db_dsn);
CLI::out('       User: ' . $ds->cfg->db_user);
CLI::out(' Client Ver: ' . $ds->db->conn->getAttribute(PDO::ATTR_CLIENT_VERSION));
CLI::out(' Server Ver: ' . $ds->db->conn->getAttribute(PDO::ATTR_SERVER_VERSION));
CLI::out('     Driver: ' . $ds->db->conn->getAttribute(PDO::ATTR_DRIVER_NAME));
CLI::out('-- Packages');
/** @var Structure $package */
foreach ($ds->packages->loaded as $package) {
    CLI::out(" $package->package_id");
    CLI::out("  Name:        $package->name");
    CLI::out("  Author:      $package->author");
    CLI::out("  Version:     $package->version");
    CLI::out("  Description: $package->description");
    CLI::out("  License:     $package->license");
}