#!/usr/bin/env php
<?php
/*
 * Dynamic Suite
 * Copyright (C) 2020 Dynamic Suite Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 */

namespace DynamicSuite;
use DynamicSuite\Core\Instance;
use DynamicSuite\Util\CLI;
use DynamicSuite\Data\Group;
use DynamicSuite\Data\Event;
use PDOException;

set_time_limit(0);
ini_set('memory_limit', -1);

require_once realpath(__DIR__ . '/create_instance.php');

/** @var Instance $ds */

// Print command usage
function printUsage(): void
{
    CLI::out('Usage: ./groups [-fhlcmda] [options ...]');
    CLI::out('Options:');
    CLI::out('  -f                          Force "YES" at all prompts');
    CLI::out('  -h, --help                  Display this help');
    CLI::out('  -l, --list                  List all groups');
    CLI::out('  -c, --create                Create a group');
    CLI::out('  -m, --modify [string]       Modify a group');
    CLI::out('  -d, --delete [string]       Delete a group');
    CLI::out('  -a, --audit [string]        Audit a groups permissions');
    CLI::out('  -p, --permissions [string]  Modify permissions for a group');
    CLI::out('  --add [string]              Add a permission to a group');
    CLI::out('  --remove [string]           Remove a permission from a group');
    CLI::out('  --clear                     Clear all permissions from a group');
}

// Make sure cached data is synced

/** @var Instance $ds */
$options = getopt('fhlcm:d:a:p:', [
    'help',
    'list',
    'create',
    'modify:',
    'delete:',
    'audit:',
    'permissions:',
    'add:',
    'remove:',
    'clear'
]);

// Show help
if (CLI::actionIs(['h', 'help'], $options)) {
    printUsage();
}

// List groups
elseif (CLI::actionIs(['l', 'list'], $options)) {
    try {
        $data = $ds->groups->getAll();
        CLI::out(CLI::table([
            'name',
            'description',
            'created_by',
            'created_on'
        ], $data));
    } catch (PDOException $exception) {
        CLI::err($exception->getMessage());
    }
}

// Create a group
elseif (CLI::actionIs(['c', 'create'], $options)) {
    try {
        $group = new Group();
        $group->name = CLI::in('Name');
        $group->description = CLI::in('Description');
        $ds->groups->create($group);
        $ds->events->create(new Event([
            'package_id' => 'dynamicsuite',
            'type' => 200,
            'affected' => $group->name,
            'message' => 'Group created'
        ]));
        CLI::out("Group added: $group->name");
    } catch (PDOException $exception) {
        CLI::err('Group not added', false);
        CLI::err($exception->getMessage());
    }
}

// Modify a group
elseif (CLI::actionIs(['m', 'modify'], $options)) {
    $group = isset($options['m']) && is_string($options['m'])
        ? $options['m']
        : $options['modify'];
    try {
        if (!$group = $ds->groups->find($group)) {
            CLI::err('Group does not exist');
        }
        $group->name = CLI::in('Name', $group->name);
        $group->description = CLI::in('Description', $group->description);
        $ds->groups->modify($group);
        $ds->events->create(new Event([
            'package_id' => 'dynamicsuite',
            'type' => 201,
            'affected' => $group->name,
            'message' => 'Group modified'
        ]));
        CLI::out("Group updated: $group->name");
    } catch (PDOException $exception) {
        CLI::err('Group not updated', false);
        CLI::err($exception->getMessage());
    }
}

// Delete a group
elseif (CLI::actionIs(['d', 'delete'], $options)) {
    $group = isset($options['d']) && is_string($options['d'])
        ? $options['d']
        : $options['delete'];
    try {
        if (!$group = $ds->groups->find($group)) {
            CLI::err('Group does not exist');
        }
        $ds->groups->delete($group);
        $ds->events->create(new Event([
            'package_id' => 'dynamicsuite',
            'type' => 202,
            'affected' => $group->name,
            'message' => 'Group deleted'
        ]));
        CLI::out("Group deleted: $group->name");
    } catch (PDOException $exception) {
        CLI::err('Group not deleted', false);
        CLI::err($exception->getMessage());
    }
}

// Audit a groups permissions
elseif (CLI::actionIs(['a', 'audit'], $options)) {
    $group = isset($options['a']) && is_string($options['a'])
        ? $options['a']
        : $options['audit'];
    try {
        if (!$group = $ds->groups->find($group)) {
            CLI::err('Group does not exist');
        }
        $data = $ds->groups->viewPermissions($group);
        CLI::out(CLI::table([
            'package_id',
            'name',
            'description'
        ], $data));
    } catch (PDOException $exception) {
        CLI::err($exception->getMessage());
    }
}

// Modify group permissions
elseif (CLI::actionIs(['p', 'permissions'], $options)) {
    $group = isset($options['p']) && is_string($options['p'])
        ? $options['p']
        : $options['permissions'];
    try {
        if (!$group = $ds->groups->find($group)) {
            CLI::err('Group does not exist');
        }
        if (isset($options['add'])) {
            if (!$permission = $ds->permissions->find($options['add'])) {
                CLI::err('Permission not found');
            }
            $ds->groups->addPermission($group, $permission);
            $ds->events->create(new Event([
                'package_id' => 'dynamicsuite',
                'type' => 250,
                'affected' => $group->name,
                'message' => 'Permission ' . $permission->shorthand() . ' added'
            ]));
        } elseif (isset($options['remove'])) {
            if (!$permission = $ds->permissions->find($options['remove'])) {
                CLI::err('Permission not found');
            }
            $ds->groups->removePermission($group, $permission);
            $ds->events->create(new Event([
                'package_id' => 'dynamicsuite',
                'type' => 251,
                'affected' => $group->name,
                'message' => 'Permission ' . $permission->shorthand() . ' removed'
            ]));
        } elseif (isset($options['clear'])) {
            $ds->groups->replacePermissions($group, []);
            $ds->events->create(new Event([
                'package_id' => 'dynamicsuite',
                'type' => 252,
                'affected' => $group->name,
                'message' => 'Permissions replaced'
            ]));
        } else {
            CLI::err('Missing flags for permission modification', false);
            printUsage();
            exit;
        }
    } catch (PDOException $exception) {
        CLI::err($exception->getMessage());
    }
}

// Missing arguments
else {
    CLI::err('Invalid usage', false);
    printUsage();
}