#!/usr/bin/env php
<?php
/*
 * Dynamic Suite
 * Copyright (C) 2020 Dynamic Suite Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 */

namespace DynamicSuite;
use DynamicSuite\Core\DynamicSuite;
use DynamicSuite\Util\CLI;
use DynamicSuite\Data\Permission;
use DynamicSuite\Data\Event;
use PDOException;

set_time_limit(0);
ini_set('memory_limit', -1);

/** @noinspection PhpIncludeInspection */
require_once realpath(__DIR__ . '/create_instance.php');

/** @var DynamicSuite $ds */

// Print command usage
function printUsage(): void
{
    CLI::out('Usage: ./permissions [-fhlcmd]');
    CLI::out('Options:');
    CLI::out('  -f                     Force "YES" at all prompts');
    CLI::out('  -h, --help             Display this help');
    CLI::out('  -l, --list             List all permissions');
    CLI::out('  -c, --create           Create a permission');
    CLI::out('  -m, --modify [string]  Modify a permission');
    CLI::out('  -d, --delete [string]  Delete a permission');
}

/** @var DynamicSuite $ds */
$options = getopt('fhlcm:d:', ['help', 'list', 'create', 'modify:', 'delete:']);

// Show help
if (CLI::actionIs(['h', 'help'], $options)) {
    printUsage();
}

// List permissions
elseif (CLI::actionIs(['l', 'list'], $options)) {
    try {
        $data = $ds->permissions->getAll();
        CLI::out(CLI::table([
            'package_id',
            'name',
            'description',
            'created_on'
        ], $data));
    } catch (PDOException $exception) {
        CLI::err($exception->getMessage());
    }
}

// Create permissions
elseif (CLI::actionIs(['c', 'create'], $options)) {
    try {
        $permission = new Permission();
        $permission->package_id = CLI::in('Package ID');
        $permission->name = CLI::in('Name');
        $permission->description = CLI::in('Description');
        $ds->permissions->create($permission);
        $ds->events->create(new Event([
            'package_id' => 'dynamicsuite',
            'type' => 100,
            'affected' => $permission->shorthand(),
            'message' => 'Permission added'
        ]));
        CLI::out('Permission added: ' . $permission->shorthand());
    } catch (PDOException $exception) {
        CLI::err('Permission not added', false);
        CLI::err($exception->getMessage());
    }
}

// Modify permissions
elseif (CLI::actionIs(['m', 'modify'], $options)) {
    $shorthand = isset($options['m']) && is_string($options['m'])
        ? $options['m']
        : $options['modify'];
    try {
        if (!$permission = $ds->permissions->find($shorthand)) {
            CLI::err('Permission not found');
        }
        $permission->package_id = CLI::in('Package ID', $permission->package_id);
        $permission->name = CLI::in('Name', $permission->name);
        $permission->description = CLI::in('Description', $permission->description);
        $ds->permissions->modify($permission);
        $ds->events->create(new Event([
            'package_id' => 'dynamicsuite',
            'type' => 101,
            'affected' => $permission->shorthand(),
            'message' => 'Permission modified'
        ]));
        CLI::out('Permission updated: ' . $permission->shorthand());
    } catch (PDOException $exception) {
        CLI::err('Permission not updated', false);
        CLI::err($exception->getMessage());
    }
}

// Delete permissions
elseif (CLI::actionIs(['d', 'delete'], $options)) {
    $shorthand = isset($options['d']) && is_string($options['d'])
        ? $options['d']
        : $options['delete'];
    try {
        /** @var Permission $permission */
        if (!$permission = $ds->permissions->find($shorthand)) {
            CLI::err('Permission not found');
        }
        if (!CLI::yn("Delete permission?")) {
            CLI::err('Cancelling');
        }
        $ds->permissions->delete($permission);
        $ds->events->create(new Event([
            'package_id' => 'dynamicsuite',
            'type' => 102,
            'affected' => $permission->shorthand(),
            'message' => 'Permission deleted'
        ]));
        CLI::out('Permission deleted: ' . $permission->shorthand());
    } catch (PDOException $exception) {
        CLI::out('Permission not deleted');
        CLI::out($exception->getMessage());
    }
}

// Missing arguments
else {
    CLI::err('Invalid usage', false);
    printUsage();
}