ALTER TABLE `ds_events`
ADD COLUMN `filter_1` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `message`,
ADD COLUMN `filter_2` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `filter_1`,
ADD COLUMN `filter_3` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `filter_2`,
ADD COLUMN `filter_4` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `filter_3`,
ADD COLUMN `filter_5` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `filter_4`;