/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `ds_events`;
DROP TABLE IF EXISTS `ds_groups`;
DROP TABLE IF EXISTS `ds_group_permissions`;
DROP TABLE IF EXISTS `ds_permissions`;
DROP TABLE IF EXISTS `ds_users`;
DROP TABLE IF EXISTS `ds_user_groups`;
DROP TABLE IF EXISTS `ds_properties`;
DROP TABLE IF EXISTS `ds_property_data`;

DROP VIEW IF EXISTS `ds_view_group_permissions`;
DROP VIEW IF EXISTS `ds_view_user_groups`;
DROP VIEW IF EXISTS `ds_view_user_permissions`;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;